# Generated by Django 6.0.6 on 2026-09-13 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('measured_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='medical_records.personprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'idempotency_key'), name='unique_profile_measurement_key')],
            },
        ),
    ]
